# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YXiMpNfsKS2Q7JMrPnSvh1GkEb0VjXCU
"""

import streamlit as st


# ============================================================
# CONFIGURAÇÃO
# ============================================================

st.set_page_config(
    page_title="NeuroBreak — Matemática das RNA",
    page_icon="🧠",
    layout="wide",
    initial_sidebar_state="expanded"
)


# ============================================================
# CSS — ESTILO DESAFIO HACKER
# ============================================================

st.markdown("""
<style>

.stApp {
    background-color: #05070a;
    color: #ffffff;
}

.main .block-container {
    max-width: 1100px;
    padding-top: 2rem;
    padding-bottom: 2rem;
}

/* Títulos */

h1, h2, h3 {
    color: #00d9ff !important;
}

p, li, label, .stMarkdown, .stText {
    color: #ffffff !important;
}


/* ============================================================
   CABEÇALHO
   ============================================================ */

.title {
    text-align: center;
    color: #00d9ff;
    font-size: 3.0rem;
    font-weight: 800;
    letter-spacing: 3px;
    margin-bottom: 0.1rem;
    text-shadow: 0 0 15px rgba(0,217,255,0.35);
}

.subtitle {
    text-align: center;
    color: #8be9fd;
    font-size: 1.05rem;
    letter-spacing: 1px;
    margin-bottom: 1.5rem;
}


/* ============================================================
   CAIXA DA MISSÃO
   ============================================================ */

.mission-box {
    border: 1px solid #00d9ff;
    border-radius: 12px;
    padding: 18px 22px;
    background: #081018;
    box-shadow: 0 0 18px rgba(0,217,255,0.08);
    margin-bottom: 20px;
}

.phase-number {
    color: #00d9ff;
    font-size: 1.05rem;
    font-weight: 700;
    letter-spacing: 2px;
}

.phase-title {
    color: #ffffff;
    font-size: 1.65rem;
    font-weight: 700;
    margin-top: 4px;
    margin-bottom: 10px;
}

.objective {
    color: #b8c7d1;
    font-size: 0.98rem;
    line-height: 1.5;
}


/* ============================================================
   CAIXA NEURAL
   ============================================================ */

.neural-box {
    background: #020509;
    border: 1px solid #173241;
    border-radius: 10px;
    padding: 16px;
    margin: 12px 0;
    font-family: monospace;
}


/* ============================================================
   RESULTADOS
   ============================================================ */

.success-box {
    border: 1px solid #00ff9d;
    background: #06130e;
    color: #00ff9d;
    border-radius: 10px;
    padding: 18px;
    margin-top: 15px;
}

.error-box {
    border: 1px solid #ff4d6d;
    background: #18070b;
    color: #ff8fa3;
    border-radius: 10px;
    padding: 15px;
    margin-top: 12px;
}


/* ============================================================
   BOTÕES
   ============================================================ */

.stButton > button {
    width: 100%;
    background-color: #07141c;
    color: #00d9ff !important;
    border: 1px solid #00d9ff;
    border-radius: 8px;
    font-weight: 700;
    padding: 0.65rem 1rem;
}

.stButton > button:hover {
    background-color: #0b2531;
    border-color: #5cecff;
    color: #ffffff !important;
}


/* ============================================================
   CAMPOS
   ============================================================ */

.stTextInput input {
    background-color: #0a1015 !important;
    color: #ffffff !important;
    border: 1px solid #00d9ff !important;
}

.stNumberInput input {
    background-color: #0a1015 !important;
    color: #ffffff !important;
}


/* ============================================================
   RADIO
   ============================================================ */

.stRadio label,
.stRadio label p,
.stRadio div[data-testid="stMarkdownContainer"] p {
    color: #FFFFFF !important;
}


/* ============================================================
   SIDEBAR
   ============================================================ */

[data-testid="stSidebar"] {
    background-color: #030609;
    border-right: 1px solid #102630;
}

[data-testid="stSidebar"] h1,
[data-testid="stSidebar"] h2,
[data-testid="stSidebar"] h3 {
    color: #00d9ff !important;
}


/* ============================================================
   MAPA DA REDE
   ============================================================ */

.block-chain {
    font-family: monospace;
    line-height: 1.65;
    font-size: 0.88rem;
}

.block-on {
    color: #00ff9d;
    text-shadow: 0 0 8px rgba(0,255,157,0.35);
}

.block-current {
    color: #00d9ff;
    text-shadow: 0 0 8px rgba(0,217,255,0.35);
}

.block-off {
    color: #43515a;
}

.metric-label {
    color: #7f9aa7;
    font-size: 0.82rem;
}

.metric-value {
    color: #ffffff;
    font-size: 1.25rem;
    font-weight: 700;
}

.small-note {
    color: #7f9aa7;
    font-size: 0.82rem;
}


/* ============================================================
   LATEX
   ============================================================ */

.katex {
    color: #ffffff !important;
}

</style>
""", unsafe_allow_html=True)


# ============================================================
# ESTADO DO JOGO
# ============================================================

if "fase" not in st.session_state:
    st.session_state.fase = 1

if "vidas" not in st.session_state:
    st.session_state.vidas = 5

if "pontos" not in st.session_state:
    st.session_state.pontos = 0

if "concluidas" not in st.session_state:
    st.session_state.concluidas = set()

if "mensagem" not in st.session_state:
    st.session_state.mensagem = ""

if "finalizado" not in st.session_state:
    st.session_state.finalizado = False


# ============================================================
# FUNÇÕES AUXILIARES
# ============================================================

def resposta_numerica(texto, esperado, tolerancia=0.01):

    try:
        valor = float(
            str(texto)
            .strip()
            .replace(",", ".")
        )

        return abs(valor - esperado) <= tolerancia

    except:
        return False


def acertou(mensagem="Resposta correta!"):

    fase_atual = st.session_state.fase

    if fase_atual not in st.session_state.concluidas:

        st.session_state.concluidas.add(fase_atual)

        st.session_state.pontos += 100

    st.session_state.mensagem = mensagem


def errou(mensagem="ERRO — Resposta incorreta."):

    st.session_state.vidas -= 1

    st.session_state.mensagem = mensagem


def proxima_fase():

    if st.session_state.fase < 25:

        st.session_state.fase += 1

        st.session_state.mensagem = ""


def reiniciar_jogo():

    st.session_state.fase = 1
    st.session_state.vidas = 5
    st.session_state.pontos = 0
    st.session_state.concluidas = set()
    st.session_state.mensagem = ""
    st.session_state.finalizado = False


def mostrar_resultado():

    if not st.session_state.mensagem:
        return

    mensagem = st.session_state.mensagem

    if mensagem.startswith("ERRO"):

        st.markdown(
            f"""
            <div class="error-box">
                ❌ {mensagem}
            </div>
            """,
            unsafe_allow_html=True
        )

    else:

        st.markdown(
            f"""
            <div class="success-box">
                ✓ {mensagem}
            </div>
            """,
            unsafe_allow_html=True
        )


def campo_resposta(key, label="Resposta"):

    return st.text_input(
        label,
        key=key,
        placeholder="Digite sua resposta..."
    )


# ============================================================
# INFORMAÇÕES DAS FASES
# ============================================================

fases = {

    1: {
        "titulo": "O NEURÔNIO ARTIFICIAL",
        "objetivo": "Reconhecer os elementos matemáticos básicos de um neurônio."
    },

    2: {
        "titulo": "COMBINAÇÃO LINEAR",
        "objetivo": "Determinar o bias a partir da combinação linear."
    },

    3: {
        "titulo": "O BIAS",
        "objetivo": "Compreender o papel matemático do bias."
    },

    4: {
        "titulo": "DECODIFICANDO O NEURÔNIO",
        "objetivo": "Identificar entradas, pesos e bias."
    },

    5: {
        "titulo": "FUNÇÃO DEGRAU",
        "objetivo": "Aplicar uma função de ativação simples."
    },

    6: {
        "titulo": "SIGMOIDE",
        "objetivo": "Calcular a saída de uma função sigmoide."
    },

    7: {
        "titulo": "RELU",
        "objetivo": "Aplicar matematicamente a função ReLU."
    },

    8: {
        "titulo": "ESCOLHA A ATIVAÇÃO",
        "objetivo": "Relacionar funções de ativação às suas propriedades."
    },

    9: {
        "titulo": "FEEDFORWARD",
        "objetivo": "Executar o fluxo matemático de um neurônio."
    },

    10: {
        "titulo": "FEEDFORWARD EM UMA CAMADA",
        "objetivo": "Calcular as saídas de dois neurônios."
    },

    11: {
        "titulo": "O ERRO DA REDE",
        "objetivo": "Calcular a diferença entre previsão e alvo."
    },

    12: {
        "titulo": "MSE",
        "objetivo": "Calcular uma função de perda MSE simples."
    },

    13: {
        "titulo": "O GRADIENTE",
        "objetivo": "Compreender o papel do gradiente no treinamento."
    },

    14: {
        "titulo": "ATUALIZAÇÃO DO PESO",
        "objetivo": "Aplicar a regra básica de atualização de um peso."
    },

    15: {
        "titulo": "BACKPROPAGATION",
        "objetivo": "Compreender o sentido do fluxo do backpropagation."
    },

    16: {
        "titulo": "BACKPROPAGATION EM UM PESO",
        "objetivo": "Calcular uma atualização simples usando gradiente."
    },

    17: {
        "titulo": "REGRA DA CADEIA",
        "objetivo": "Relacionar derivadas em uma cadeia de cálculo."
    },

    18: {
        "titulo": "SIGMOIDE + MSE",
        "objetivo": "Relacionar ativação, perda e gradiente."
    },

    19: {
        "titulo": "SIGMOIDE + ENTROPIA CRUZADA",
        "objetivo": "Reconhecer uma combinação usada no treinamento de classificação."
    },

    20: {
        "titulo": "REGULARIZAÇÃO L1",
        "objetivo": "Calcular a penalização baseada no valor absoluto dos pesos."
    },

    21: {
        "titulo": "L1 + λ",
        "objetivo": "Incorporar a penalização L1 à função objetivo."
    },

    22: {
        "titulo": "REGULARIZAÇÃO L2",
        "objetivo": "Calcular a penalização baseada no quadrado dos pesos."
    },

    23: {
        "titulo": "L1 × L2",
        "objetivo": "Comparar matematicamente as duas penalizações."
    },

    24: {
        "titulo": "DROPOUT",
        "objetivo": "Aplicar uma máscara de ativações durante o treinamento."
    },

    25: {
        "titulo": "DESAFIO FINAL — REGULARIZE A REDE",
        "objetivo": "Integrar neurônio, ativação, erro e regularização."
    }
}


# ============================================================
# SIDEBAR
# ============================================================

with st.sidebar:

    st.markdown("## 🧠 NEUROBREAK")

    st.markdown("### STATUS DA REDE")

    st.markdown(
        f"""
        <div class="metric-label">FASE</div>
        <div class="metric-value">
            {st.session_state.fase} / 25
        </div>
        """,
        unsafe_allow_html=True
    )

    st.markdown(
        f"""
        <div class="metric-label">PONTOS</div>
        <div class="metric-value">
            {st.session_state.pontos}
        </div>
        """,
        unsafe_allow_html=True
    )

    chaves = "🔑 " * max(
        st.session_state.vidas,
        0
    )

    st.markdown(
        f"""
        <div class="metric-label">CHAVES DE ACESSO</div>
        <div class="metric-value">
            {chaves}
        </div>
        """,
        unsafe_allow_html=True
    )

    st.progress(
        min(
            len(st.session_state.concluidas) / 25,
            1.0
        )
    )

    st.markdown("---")

    st.markdown("### 🔗 MAPA DA REDE")

    for i in range(1, 26):

        if i in st.session_state.concluidas:

            classe = "block-on"
            simbolo = "●"

        elif i == st.session_state.fase:

            classe = "block-current"
            simbolo = "◆"

        else:

            classe = "block-off"
            simbolo = "○"

        titulo_curto = fases[i]["titulo"]

        st.markdown(
            f"""
            <div class="block-chain {classe}">
                {simbolo} {i:02d} — {titulo_curto}
            </div>
            """,
            unsafe_allow_html=True
        )

    st.markdown("---")

    st.markdown(
        """
        <div class="small-note">

        OBJETIVO DA MISSÃO

        <br><br>

        Dominar a matemática essencial das
        redes neurais artificiais, passando
        por neurônios, ativação, treinamento
        e regularização.

        </div>
        """,
        unsafe_allow_html=True
    )

    st.markdown("---")

    if st.button("🔄 REINICIAR JOGO"):

        reiniciar_jogo()

        st.rerun()


# ============================================================
# CABEÇALHO PRINCIPAL
# ============================================================

st.markdown(
    '<div class="title">🧠 NEUROBREAK</div>',
    unsafe_allow_html=True
)

st.markdown(
    '<div class="subtitle">MATEMÁTICA DAS REDES NEURAIS ARTIFICIAIS</div>',
    unsafe_allow_html=True
)


# ============================================================
# TELA FINAL
# ============================================================

if st.session_state.finalizado:

    st.markdown(
        """
        <div class="mission-box">

            <div class="phase-number">
                ██████████████████████████████
            </div>

            <div class="phase-title">
                NÚCLEO NEURAL DESBLOQUEADO
            </div>

            <div class="objective">
                Todos os módulos matemáticos da rede
                foram processados.
                A arquitetura foi regularizada e
                o sistema está operacional.
            </div>

        </div>
        """,
        unsafe_allow_html=True
    )

    st.markdown(
        f"""
        <div class="success-box">

            <h2>🎉 PARABÉNS!</h2>

            <h3>🧠 MISSÃO CUMPRIDA</h3>

            <p>
                Você concluiu as <strong>25 fases</strong>
                do NeuroBreak.
            </p>

            <p>
                <strong>
                    Pontuação final:
                    {st.session_state.pontos}
                </strong>
            </p>

            <p>
                Você passou por neurônios artificiais,
                combinação linear, funções de ativação,
                feedforward, erro, MSE,
                gradiente, backpropagation,
                regra da cadeia, L1, L2 e Dropout.
            </p>

        </div>
        """,
        unsafe_allow_html=True
    )

    st.balloons()

    st.stop()


# ============================================================
# IDENTIFICAÇÃO DA FASE
# ============================================================

fase = st.session_state.fase
info = fases[fase]


# IMPORTANTE:
# O HTML está inteiro dentro de UMA chamada markdown
# com unsafe_allow_html=True.

st.markdown(
    f"""
<div class="mission-box">
    <div class="phase-number">FASE {fase:02d} / 25</div>
    <div class="phase-title">{info["titulo"]}</div>
    <div class="objective">{info["objetivo"]}</div>
</div>
""",
    unsafe_allow_html=True
)


# ============================================================
# FASE 1
# ============================================================

if fase == 1:

    st.markdown("### 🔐 Identifique o elemento")

    st.markdown(
        """
        <div class="neural-box">

        Um neurônio artificial recebe entradas,
        multiplica cada entrada por um peso,
        soma os resultados e aplica uma função
        de ativação.

        </div>
        """,
        unsafe_allow_html=True
    )

    op = st.radio(
        "Qual expressão representa a combinação linear de um neurônio?",
        [
            "A) x₁ + x₂ + b",
            "B) w₁x₁ + w₂x₂ + b",
            "C) f(x₁) + f(x₂)",
            "D) w₁ + w₂ + x₁ + x₂"
        ],
        key="f1"
    )

    if st.button("VERIFICAR FASE 1"):

        if op.startswith("B"):

            acertou(
                "Correto! O neurônio primeiro calcula uma combinação linear."
            )

        else:

            errou(
                "ERRO — A combinação linear utiliza pesos, entradas e bias."
            )


# ============================================================
# FASE 2 — ALTERADA
# ============================================================

elif fase == 2:

    st.markdown("### 🧮 Determine o bias")

    st.markdown(
        """
        O neurônio realiza a combinação linear:

        \[
        z=w_1x_1+w_2x_2+b
        \]

        São conhecidos:

        \[
        x_1=2
        \]

        \[
        x_2=3
        \]

        \[
        w_1=0,5
        \]

        \[
        w_2=-0,2
        \]

        e o resultado da combinação linear é:

        \[
        z=0,5
        \]

        **Determine o valor do bias \(b\).**
        """
    )

    r = campo_resposta(
        "f2",
        "Valor do bias b"
    )

    if st.button("VERIFICAR FASE 2"):

        if resposta_numerica(r, 0.5):

            acertou(
                "Correto! 0,5 = 0,5(2) + (-0,2)(3) + b, portanto b = 0,5."
            )

        else:

            errou(
                "ERRO — Substitua os valores na combinação linear e isole o bias."
            )


# ============================================================
# FASE 3
# ============================================================

elif fase == 3:

    st.markdown("### 🧮 O bias desloca a combinação linear")

    st.latex(
        r"z=w_1x_1+w_2x_2+b"
    )

    st.markdown(
        """
        Considere:

        \(x_1=1\)

        \(x_2=2\)

        \(w_1=2\)

        \(w_2=1\)

        \(b=-1\)

        **Qual é o valor de \(z\)?**
        """
    )

    r = campo_resposta("f3")

    if st.button("VERIFICAR FASE 3"):

        if resposta_numerica(r, 3):

            acertou(
                "Correto! O bias é somado à combinação linear."
            )

        else:

            errou(
                "ERRO — Primeiro calcule w₁x₁ + w₂x₂ e depois some o bias."
            )


# ============================================================
# FASE 4
# ============================================================

elif fase == 4:

    st.markdown("### 🔎 Decodifique o neurônio")

    st.markdown(
        """
        <div class="neural-box">

        z = (0,8)(2) + (-0,5)(4) + 0,2

        </div>
        """,
        unsafe_allow_html=True
    )

    op = st.radio(
        "Qual elemento representa o bias?",
        [
            "A) 0,8",
            "B) 2",
            "C) -0,5",
            "D) 0,2"
        ],
        key="f4"
    )

    if st.button("VERIFICAR FASE 4"):

        if op.startswith("D"):

            acertou(
                "Correto! O termo independente 0,2 é o bias."
            )

        else:

            errou(
                "ERRO — O bias é o termo somado independentemente das entradas."
            )


# ============================================================
# FASE 5
# ============================================================

elif fase == 5:

    st.markdown("### 🧮 Função degrau")

    st.latex(
        r"""
        f(z)=
        \begin{cases}
        1,&z\geq0\\
        0,&z<0
        \end{cases}
        """
    )

    st.markdown(
        """
        Para \(z=-2\), qual é a saída?
        """
    )

    r = campo_resposta("f5")

    if st.button("VERIFICAR FASE 5"):

        if resposta_numerica(r, 0, 0.0):

            acertou(
                "Correto! Como z < 0, a função degrau retorna 0."
            )

        else:

            errou(
                "ERRO — Na função degrau, valores negativos produzem saída 0."
            )


# ============================================================
# FASE 6
# ============================================================

elif fase == 6:

    st.markdown("### 🧮 Ativação sigmoide")

    st.latex(
        r"\sigma(z)=\frac{1}{1+e^{-z}}"
    )

    st.markdown(
        """
        Para facilitar o cálculo manual, considere:

        \(e^{-1}\approx0,37\)

        Calcule aproximadamente \(\sigma(1)\).
        """
    )

    r = campo_resposta("f6")

    if st.button("VERIFICAR FASE 6"):

        if resposta_numerica(r, 0.73, 0.03):

            acertou(
                "Correto! A sigmoide transforma z=1 em aproximadamente 0,73."
            )

        else:

            errou(
                "ERRO — Use 1/(1+e⁻¹) e a aproximação fornecida."
            )


# ============================================================
# FASE 7
# ============================================================

elif fase == 7:

    st.markdown("### 🧮 ReLU")

    st.latex(
        r"ReLU(z)=\max(0,z)"
    )

    st.markdown(
        """
        Calcule a saída para \(z=-3,5\).
        """
    )

    r = campo_resposta("f7")

    if st.button("VERIFICAR FASE 7"):

        if resposta_numerica(r, 0):

            acertou(
                "Correto! A ReLU zera valores negativos."
            )

        else:

            errou(
                "ERRO — ReLU retorna max(0,z)."
            )


# ============================================================
# FASE 8
# ============================================================

elif fase == 8:

    st.markdown("### 🧠 Escolha a função")

    op = st.radio(
        "Qual função é conhecida por produzir valores entre 0 e 1?",
        [
            "A) ReLU",
            "B) Sigmoide",
            "C) Função degrau sem limitação",
            "D) Combinação linear"
        ],
        key="f8"
    )

    if st.button("VERIFICAR FASE 8"):

        if op.startswith("B"):

            acertou(
                "Correto! A sigmoide produz valores no intervalo (0,1)."
            )

        else:

            errou(
                "ERRO — Pense na saída da função usada frequentemente em classificação binária."
            )


# ============================================================
# FASE 9
# ============================================================

elif fase == 9:

    st.markdown("### 🧮 Execute um feedforward")

    st.markdown(
        """
        **Entradas**

        \(x_1=2\)

        \(x_2=1\)

        **Pesos**

        \(w_1=0,5\)

        \(w_2=1\)

        **Bias**

        \(b=-0,5\)

        Primeiro calcule \(z\).

        Depois aplique ReLU.
        """
    )

    st.latex(
        r"z=w_1x_1+w_2x_2+b"
    )

    r = campo_resposta("f9")

    if st.button("VERIFICAR FASE 9"):

        if resposta_numerica(r, 1.5):

            acertou(
                "Correto! z=1,5 e ReLU(1,5)=1,5."
            )

        else:

            errou(
                "ERRO — Calcule z antes de aplicar a ReLU."
            )


# ============================================================
# FASE 10
# ============================================================

elif fase == 10:

    st.markdown("### 🧮 Uma camada, dois neurônios")

    st.markdown(
        """
        **Entradas**

        \(x_1=1\)

        \(x_2=2\)

        **Neurônio A**

        \(w_1=1\)

        \(w_2=0,5\)

        \(b=0\)

        **Neurônio B**

        \(w_1=-1\)

        \(w_2=1\)

        \(b=0\)

        Calcule a saída **linear** de cada neurônio.
        """
    )

    a = st.text_input(
        "Saída do neurônio A",
        key="f10a"
    )

    b = st.text_input(
        "Saída do neurônio B",
        key="f10b"
    )

    if st.button("VERIFICAR FASE 10"):

        if (
            resposta_numerica(a, 2.0)
            and
            resposta_numerica(b, 1.0)
        ):

            acertou(
                "Correto! As duas combinações lineares foram calculadas."
            )

        else:

            errou(
                "ERRO — A=1(1)+0,5(2) e B=-1(1)+1(2)."
            )


# ============================================================
# FASE 11
# ============================================================

elif fase == 11:

    st.markdown("### 🧮 Calcule o erro")

    st.markdown(
        """
        A rede produziu \(\hat{y}=0,7\).

        O valor verdadeiro é \(y=1\).

        Considere o erro simples:
        """
    )

    st.latex(
        r"e=y-\hat{y}"
    )

    r = campo_resposta("f11")

    if st.button("VERIFICAR FASE 11"):

        if resposta_numerica(r, 0.3):

            acertou(
                "Correto! O erro simples é 1 - 0,7 = 0,3."
            )

        else:

            errou(
                "ERRO — Subtraia a previsão do valor alvo."
            )


# ============================================================
# FASE 12
# ============================================================

elif fase == 12:

    st.markdown("### 🧮 Função de perda MSE")

    st.latex(
        r"""
        MSE=
        \frac{1}{n}
        \sum_{i=1}^{n}
        (y_i-\hat y_i)^2
        """
    )

    st.markdown(
        """
        Para um único exemplo:

        \(y=1\)

        \(\hat y=0,8\)

        Calcule o MSE desse exemplo.
        """
    )

    r = campo_resposta("f12")

    if st.button("VERIFICAR FASE 12"):

        if resposta_numerica(r, 0.04):

            acertou(
                "Correto! (1 - 0,8)² = 0,04."
            )

        else:

            errou(
                "ERRO — Eleve o erro ao quadrado."
            )


# ============================================================
# FASE 13
# ============================================================

elif fase == 13:

    st.markdown("### 🧠 O sentido do gradiente")

    op = st.radio(
        "Durante o treinamento, o gradiente indica principalmente:",
        [
            "A) A quantidade de neurônios da rede",
            "B) A direção de maior crescimento da função de perda",
            "C) O número de épocas do treinamento",
            "D) O valor do bias"
        ],
        key="f13"
    )

    if st.button("VERIFICAR FASE 13"):

        if op.startswith("B"):

            acertou(
                "Correto! O gradiente fornece a direção de crescimento da função de perda."
            )

        else:

            errou(
                "ERRO — O gradiente é usado para orientar a atualização dos parâmetros."
            )


# ============================================================
# FASE 14
# ============================================================

elif fase == 14:

    st.markdown("### 🧮 Atualize o peso")

    st.latex(
        r"""
        w_{novo}
        =
        w-\eta
        \frac{\partial L}{\partial w}
        """
    )

    st.markdown(
        """
        Considere:

        \(w=0,8\)

        \(\eta=0,1\)

        \(\frac{\partial L}{\partial w}=2\)

        Calcule o novo peso.
        """
    )

    r = campo_resposta("f14")

    if st.button("VERIFICAR FASE 14"):

        if resposta_numerica(r, 0.6):

            acertou(
                "Correto! w_novo = 0,8 - 0,1(2) = 0,6."
            )

        else:

            errou(
                "ERRO — Subtraia taxa de aprendizagem × gradiente."
            )


# ============================================================
# FASE 15
# ============================================================

elif fase == 15:

    st.markdown("### 🧠 Fluxo do backpropagation")

    op = st.radio(
        "O backpropagation propaga principalmente o quê da saída em direção às camadas anteriores?",
        [
            "A) Os dados brutos",
            "B) O gradiente do erro",
            "C) Os neurônios desligados pelo Dropout",
            "D) O valor do bias"
        ],
        key="f15"
    )

    if st.button("VERIFICAR FASE 15"):

        if op.startswith("B"):

            acertou(
                "Correto! O gradiente do erro é propagado para calcular atualizações dos pesos."
            )

        else:

            errou(
                "ERRO — O backpropagation utiliza gradientes para atualizar os parâmetros."
            )


# ============================================================
# FASE 16
# ============================================================

elif fase == 16:

    st.markdown("### 🧮 Backpropagation: atualização")

    st.markdown(
        """
        Um peso possui valor:

        \(w=-0,3\)

        A taxa de aprendizagem é:

        \(\eta=0,2\)

        O gradiente calculado é:

        \(\frac{\partial L}{\partial w}=-1,5\)
        """
    )

    st.latex(
        r"""
        w_{novo}
        =
        w-\eta
        \frac{\partial L}{\partial w}
        """
    )

    r = campo_resposta("f16")

    if st.button("VERIFICAR FASE 16"):

        if resposta_numerica(r, 0.0):

            acertou(
                "Correto! -0,3 - 0,2(-1,5) = 0."
            )

        else:

            errou(
                "ERRO — Cuidado com o sinal negativo do gradiente."
            )


# ============================================================
# FASE 17
# ============================================================

elif fase == 17:

    st.markdown("### 🧮 Regra da cadeia")

    st.latex(
        r"""
        \frac{dL}{dw}
        =
        \frac{dL}{dy}
        \cdot
        \frac{dy}{dz}
        \cdot
        \frac{dz}{dw}
        """
    )

    st.markdown(
        """
        Considere:

        \[
        \frac{dL}{dy}=2
        \]

        \[
        \frac{dy}{dz}=0,5
        \]

        \[
        \frac{dz}{dw}=3
        \]

        Calcule \(\frac{dL}{dw}\).
        """
    )

    r = campo_resposta("f17")

    if st.button("VERIFICAR FASE 17"):

        if resposta_numerica(r, 3):

            acertou(
                "Correto! Pela regra da cadeia: 2 × 0,5 × 3 = 3."
            )

        else:

            errou(
                "ERRO — Multiplique as três derivadas."
            )


# ============================================================
# FASE 18
# ============================================================

elif fase == 18:

    st.markdown("### 🧮 Sigmoide + MSE")

    st.markdown(
        """
        Para esta fase, considere um valor simplificado
        da derivada da sigmoide:

        \[
        \sigma'(z)=0,2
        \]

        e o erro:

        \[
        \hat y-y=-0,3
        \]

        Considere, para este exercício:
        """
    )

    st.latex(
        r"""
        \frac{dL}{dz}
        =
        (\hat y-y)\sigma'(z)
        """
    )

    st.markdown(
        """
        Calcule \(\frac{dL}{dz}\).
        """
    )

    r = campo_resposta("f18")

    if st.button("VERIFICAR FASE 18"):

        if resposta_numerica(r, -0.06):

            acertou(
                "Correto! (-0,3)(0,2) = -0,06."
            )

        else:

            errou(
                "ERRO — Multiplique o erro pela derivada fornecida."
            )


# ============================================================
# FASE 19
# ============================================================

elif fase == 19:

    st.markdown("### 🧠 Combinação usada em classificação")

    st.markdown(
        """
        Diferentes combinações de funções de ativação
        e funções de perda podem ser utilizadas no
        treinamento de redes neurais.
        """
    )

    op = st.radio(
        "Qual combinação é apresentada para classificação binária?",
        [
            "A) ReLU + MSE",
            "B) Sigmoide + Entropia Cruzada",
            "C) ReLU + MAE",
            "D) Degrau + MAPE"
        ],
        key="f19"
    )

    if st.button("VERIFICAR FASE 19"):

        if op.startswith("B"):

            acertou(
                "Correto! Sigmoide + Entropia Cruzada."
            )

        else:

            errou(
                "ERRO — Revise as combinações entre ativação e função de perda."
            )


# ============================================================
# FASE 20
# ============================================================

elif fase == 20:

    st.markdown("### 🔥 Regularização L1")

    st.markdown(
        """
        A penalização L1 utiliza o **valor absoluto**
        dos pesos.
        """
    )

    st.latex(
        r"L_1=\sum_i |w_i|"
    )

    st.markdown(
        """
        Considere:

        \[
        w=[2,-3,0,1]
        \]

        Calcule a penalização L1.
        """
    )

    r = campo_resposta("f20")

    if st.button("VERIFICAR FASE 20"):

        if resposta_numerica(r, 6):

            acertou(
                "Correto! |2| + |-3| + |0| + |1| = 6."
            )

        else:

            errou(
                "ERRO — Na L1, use o valor absoluto de cada peso."
            )


# ============================================================
# FASE 21
# ============================================================

elif fase == 21:

    st.markdown("### 🧮 L1 + λ")

    st.latex(
        r"""
        L_{reg}
        =
        L+\lambda\sum_i|w_i|
        """
    )

    st.markdown(
        """
        Considere:

        \(L=0,4\)

        \(\lambda=0,1\)

        \[
        w=[2,-3,0,1]
        \]

        Qual é o valor da função objetivo regularizada?
        """
    )

    r = campo_resposta("f21")

    if st.button("VERIFICAR FASE 21"):

        if resposta_numerica(r, 1.0):

            acertou(
                "Correto! 0,4 + 0,1(6) = 1,0."
            )

        else:

            errou(
                "ERRO — Primeiro calcule a penalização L1 e depois multiplique por λ."
            )


# ============================================================
# FASE 22
# ============================================================

elif fase == 22:

    st.markdown("### ⚡ Regularização L2")

    st.markdown(
        """
        A penalização L2 utiliza o quadrado dos pesos.
        """
    )

    st.latex(
        r"L_2=\sum_i w_i^2"
    )

    st.markdown(
        """
        Considere:

        \[
        w=[2,-1,0,3]
        \]

        Calcule a penalização L2.
        """
    )

    r = campo_resposta("f22")

    if st.button("VERIFICAR FASE 22"):

        if resposta_numerica(r, 14):

            acertou(
                "Correto! 2² + (-1)² + 0² + 3² = 14."
            )

        else:

            errou(
                "ERRO — Na L2, eleve cada peso ao quadrado."
            )


# ============================================================
# FASE 23
# ============================================================

elif fase == 23:

    st.markdown("### ⚔️ L1 × L2")

    st.markdown(
        """
        Considere os mesmos pesos:

        \[
        w=[2,-1,0,3]
        \]

        **L1**

        \[
        |2|+|-1|+|0|+|3|
        \]

        **L2**

        \[
        2^2+(-1)^2+0^2+3^2
        \]
        """
    )

    op = st.radio(
        "Qual afirmação está correta?",
        [
            "A) L1 = 6 e L2 = 14",
            "B) L1 = 14 e L2 = 6",
            "C) L1 = 5 e L2 = 12",
            "D) L1 = 6 e L2 = 12"
        ],
        key="f23"
    )

    if st.button("VERIFICAR FASE 23"):

        if op.startswith("A"):

            acertou(
                "Correto! L1 soma magnitudes; L2 soma quadrados."
            )

        else:

            errou(
                "ERRO — Calcule separadamente valor absoluto e quadrado."
            )


# ============================================================
# FASE 24
# ============================================================

elif fase == 24:

    st.markdown("### 🎯 Dropout")

    st.markdown(
        """
        Durante o treinamento, considere quatro ativações:

        \[
        h=[0,8,\ 0,4,\ 0,6,\ 0,2]
        \]

        A máscara de Dropout sorteada foi:

        \[
        m=[1,\ 0,\ 1,\ 0]
        \]

        Neste exercício, considere simplesmente:

        \[
        h'=h\odot m
        \]

        Quantas ativações permanecem ativas?
        """
    )

    r = campo_resposta("f24")

    if st.button("VERIFICAR FASE 24"):

        if resposta_numerica(r, 2):

            acertou(
                "Correto! A máscara [1,0,1,0] mantém duas ativações."
            )

        else:

            errou(
                "ERRO — Os valores 1 da máscara indicam as ativações mantidas."
            )


# ============================================================
# FASE 25 — DESAFIO FINAL
# ============================================================

elif fase == 25:

    st.markdown("### 🚨 NÚCLEO FINAL — REGULARIZE A REDE")

    st.markdown(
        """
        <div class="neural-box">

        A rede precisa passar pelo último teste matemático.

        Execute o cálculo do neurônio,
        determine a saída da função de ativação
        e calcule a penalização L1.

        </div>
        """,
        unsafe_allow_html=True
    )

    st.markdown(
        """
        ### NEURÔNIO

        **Entradas**

        \[
        x_1=0,6
        \]

        \[
        x_2=0,2
        \]

        **Pesos**

        \[
        w_1=0,5
        \]

        \[
        w_2=-0,4
        \]

        **Bias**

        \[
        b=0,1
        \]

        O neurônio utiliza **sigmoide**.

        O alvo é:

        \[
        y=1
        \]

        Para facilitar o cálculo, use:

        \[
        e^{-0,32}\approx0,73
        \]

        ---

        ### ETAPA 1

        Calcule:

        \[
        z=w_1x_1+w_2x_2+b
        \]

        ---

        ### ETAPA 2

        Calcule aproximadamente a saída da sigmoide:

        \[
        \sigma(z)=\frac{1}{1+e^{-z}}
        \]

        ---

        ### ETAPA 3

        Para a regularização L1, considere:

        \[
        L_1=|w_1|+|w_2|
        \]

        e:

        \[
        \lambda=0,1
        \]

        Calcule:

        \[
        \lambda L_1
        \]
        """
    )

    z = st.text_input(
        "1) Valor de z",
        key="f25z"
    )

    saida = st.text_input(
        "2) Saída aproximada da sigmoide",
        key="f25s"
    )

    l1 = st.text_input(
        "3) Penalização L1 × λ",
        key="f25l1"
    )

    if st.button("🔓 DESBLOQUEAR NÚCLEO FINAL"):

        ok_z = resposta_numerica(
            z,
            0.32,
            0.01
        )

        ok_s = resposta_numerica(
            saida,
            0.58,
            0.03
        )

        ok_l1 = resposta_numerica(
            l1,
            0.09,
            0.01
        )

        if ok_z and ok_s and ok_l1:

            acertou(
                "NÚCLEO DESBLOQUEADO! Você integrou neurônio, ativação e regularização."
            )

            st.session_state.finalizado = True

            st.rerun()

        else:

            errou(
                "ERRO — Revise as três etapas: combinação linear, sigmoide e penalização L1."
            )


# ============================================================
# MOSTRAR RESULTADO
# ============================================================

mostrar_resultado()


# ============================================================
# PRÓXIMA FASE
# ============================================================

if (
    fase in st.session_state.concluidas
    and fase < 25
):

    st.markdown("<br>", unsafe_allow_html=True)

    if st.button("➡️ PRÓXIMA FASE"):

        proxima_fase()

        st.rerun()


# ============================================================
# GAME OVER
# ============================================================

if st.session_state.vidas <= 0:

    st.error(
        "🔒 As chaves de acesso foram esgotadas. "
        "Reinicie o jogo para tentar novamente."
    )

    st.stop()